### ISSUE TITLE
[18:56:48 ERR] You must specify either 'Key' (ConsoleKey value) or 'KeyName' (ConsoleKey enum name) for

### ISSUE THREAD

**Issue by teehehe** [julianperrott/WowClassicGrindBot#11]
[18:56:48 ERR] You must specify either 'Key' (ConsoleKey value) or 'KeyName' (ConsoleKey enum name) for

2020-09-10 18:56:48.200 -07:00 [ERR] Failed to read AH prices.Could not find a part of the path 'D:\GitHub\Auc-Stat-Simple.lua.location'.
2020-09-10 18:56:48.357 -07:00 [INF] Processing requirement Frost Armor : not Frost Armor
2020-09-10 18:56:48.358 -07:00 [INF] Processing requirement Arcane Intellect : not Arcane Intellect
2020-09-10 18:56:48.359 -07:00 [INF] Processing requirement Conjure Water : not BagItem:2288:4
2020-09-10 18:56:48.377 -07:00 [INF] Processing requirement Conjure Food : not BagItem:5349:4
2020-09-10 18:56:48.408 -07:00 [INF] Processing requirement Low Health : Health%<80
2020-09-10 18:56:48.416 -07:00 [INF] Processing requirement Drink : Mana%<70
2020-09-10 18:56:48.427 -07:00 [ERR] You must specify either 'Key' (ConsoleKey value) or 'KeyName' (ConsoleKey enum name) for 

my mage.json

{
  "ClassName": "Mage",
  "Loot": true,

  "PathFilename": "mage10durotar.json",
  "SpiritPathFilename": "durotargy.json",
  "PathThereAndBack": true,
  "PathReduceSteps": false,

  "Pull": {
    "Sequence": [
      {
        "Name": "Interact",
        "Key": "H",
        "Cooldown": 1,
        "DelayAfterCast": 0
      },
      {
        "Name": "Frostbolt",
        "HasCastBar": true,
        "StopBeforeCast": true,
        "Key": "1",
        "ManaRequirement": 35
      },
      {
        "Name": "Arcane Missiles",
        "HasCastBar": true,
        "Key": "0",
        "MinMana": 140,
        "Cooldown": 60,
        "DelaybeforeCast": 1000
      }
    ]
  },
  "Combat": {
    "Sequence": [
      {
        "Name": "Interact",
        "Key": "H",
        "Cooldown": 2,
        "DelayAfterCast": 0
      },
      {
        "Name": "Fireblast",
        "HasCastBar": false,
        "StopBeforeCast": false,
        "Key": "5",
        "ManaRequirement": 75,
        "Cooldown": 8
      },
      {
        "Name": "Fireball",
        "HasCastBar": true,
        "StopBeforeCast": true,
        "Key": "2",
        "ManaRequirement": 65
      }
    ]
  },
  "Parallel": {
    "Sequence": [
      {
        "Name": "Low Health",
        "HasCastBar": true,
        "StopBeforeCast": true,
        "Key": "6",
        "Requirement": "Health%<80",
        "Cooldown": 10,
        "Log": false
      },
      {
        "Name": "Drink",
        "HasCastBar": true,
        "StopBeforeCast": true,
        "Key": "7",
        "Requirement": "Mana%<70",
        "Cooldown": 10,
        "Log": false
      }
    ]
    },

  "Adhoc": {
    "Sequence": [
      {
        "Name": "Frost Armor",
        "StopBeforeCast": false,
        "Key": "3",
        "ManaRequirement": 60,
        "Requirement": "not Frost Armor"
      },
      {
        "Name": "Arcane Intellect",
        "StopBeforeCast": false,
        "Key": "4",
        "MinMana": 60,
        "Requirement": "not Arcane Intellect",
        "Log": false
      },
      {
        "Name": "Conjure Water",
        "HasCastBar": true,
        "StopBeforeCast": true,
        "Key": "9",
        "Requirement": "not BagItem:2288:4",
        "Cooldown": 30,
        "Log": false
      },
      {
        "Name": "Conjure Food",
        "HasCastBar": true,
        "StopBeforeCast": true,
        "Key": "8",
        "Requirement": "not BagItem:5349:4",
        "Cooldown": 30,
        "Log": false
      }
    ]
  }
}

that all it says so not sure what key its looking for? bot still functioning though so not sure what its trying to find a key for all abilities are firing correctly.

**Comment by julianperrott** [comment]
It is trying to setup a key for blink, but it is not essential.

```
  "Blink":{
    "Name": "Blink",
    "Key": "T"
  },

```
e.g. see in here:
[Mage.txt](https://github.com/julianperrott/WowClassicGrindBot/files/5208640/Mage.txt)

**Comment by teehehe** [comment]
> It is trying to setup a key for blink, but it is not essential.
> 
> ```
>   "Blink":{
>     "Name": "Blink",
>     "Key": "T"
>   },
> ```
> 
> e.g. see in here:
> [Mage.txt](https://github.com/julianperrott/WowClassicGrindBot/files/5208640/Mage.txt)

Even tho in my json i dont have blink listed?

**Comment by julianperrott** [comment]
Yes, I need to fix this realy.
