### ISSUE TITLE
force face creature

### ISSUE THREAD

**Issue by teehehe** [julianperrott/WowClassicGrindBot#12]
So i understand we are using the H key interact with target to face, however when the mobs are low they may run thru the character and end up behind them the bot stands there spamming target not in view and never will reface them essentially. I have defined interact in the class.json and tried different cooldown variations and still seems to happen. Any insight on how to fix this? class would be a mage.

**Comment by julianperrott** [comment]
I don't fight mobs which run which makes things easier, I stick to beasts mostly. in the combat sequence I usually include an interact on a long cooldown (12 seconds). Also a UI Error is sometimes raised such as Bad Attack Facing which is used by method InteractOnUIError() in [CastingHandler.cs](https://github.com/julianperrott/WowClassicGrindBot/blob/master/Libs/Goals/CastingHandler.cs)
to try to face the target.

` 
     "Combat": {
    "Sequence": [
      {
        "Name": "Healing Potion",
        "Key": "F4",
        "Requirement": "Health%<10",
        "Cooldown": 60,
        "Log": false
      },
      {
        "Name": "Interact",
        "Key": "H",
        "Cooldown": 12,
        "DelayAfterCast": 0
      },
      {
        "Name": "Fireblast",
        "HasCastBar": false,
        "StopBeforeCast": false,
        "Key": "0",
        "ManaRequirement": 75,
        "Cooldown": 8
      },
      {
        "Name": "Fireball",
        "HasCastBar": true,
        "Key": "2",
        "ManaRequirement": 65
      }
    ]
  }
`

**Comment by teehehe** [comment]
> I don't fight mobs which run which makes things easier, I stick to beasts mostly. in the combat sequence I usually include an interact on a long cooldown (12 seconds). Also a UI Error is sometimes raised such as Bad Attack Facing which is used by method InteractOnUIError() in [CastingHandler.cs](https://github.com/julianperrott/WowClassicGrindBot/blob/master/Libs/Goals/CastingHandler.cs)
> to try to face the target.
> 
> ` "Combat": { "Sequence": [ { "Name": "Healing Potion", "Key": "F4", "Requirement": "Health%<10", "Cooldown": 60, "Log": false }, { "Name": "Interact", "Key": "H", "Cooldown": 12, "DelayAfterCast": 0 }, { "Name": "Fireblast", "HasCastBar": false, "StopBeforeCast": false, "Key": "0", "ManaRequirement": 75, "Cooldown": 8 }, { "Name": "Fireball", "HasCastBar": true, "Key": "2", "ManaRequirement": 65 } ] }`

thats essentially how mine looks. i looked at a lot of your already created profiles however I am on horde. Do you have a list of  good horde spots or beasts in general? I am currently in barrens doing plainstriders i kinda thought they are beast but they run at low hp as well. I currently have it to arcane missle when they are low hp and that kinda forces the char to follow it

**Comment by julianperrott** [comment]
Sorry no horde spots. Good idea with the arcane missiles. I assume you have click to move turned on?

**Comment by teehehe** [comment]
> Sorry no horde spots. Good idea with the arcane missiles. I assume you have click to move turned on?

correct, i actually do flameblast and then arcane missle at 15% hp in hopes to burst them down before they can run or so arcane missle will turn to face as they run. I also checked and plainstriders are labeled as beast in game so not sure why they are fleeing.
