### ISSUE TITLE
inccorect sample profile mage6.json

### ISSUE THREAD

**Issue by teehehe** [julianperrott/WowClassicGrindBot#14]
{
          "Name": "Low Health",
          "HasCastBar": true,
          "StopBeforeCast": true,
          "Key": "6",
          "Requirement": "TargetHealth%<90",
          "Cooldown": 10,
          "Log": false
        },

should be 

    {
          "Name": "Low Health",
          "HasCastBar": true,
          "StopBeforeCast": true,
          "Key": "6",
          "Requirement": "Health%<90",
          "Cooldown": 10,
          "Log": false
        },

and then 

      {
          "Name": "Conjure Food",
          "HasCastBar": true,
          "StopBeforeCast": true,
          "Key": "8",
          "Requirement": "not BagItem:5350:4",
          "Cooldown": 30,
          "Log": false
        }

should be 

    {
          "Name": "Conjure Food",
          "HasCastBar": true,
          "StopBeforeCast": true,
          "Key": "8",
          "Requirement": "not BagItem:5349:4",
          "Cooldown": 30,
          "Log": false
        }

**Comment by julianperrott** [comment]
ok
