### ISSUE TITLE
GY Issue

### ISSUE THREAD

**Issue by teehehe** [julianperrott/WowClassicGrindBot#19]
![route](https://user-images.githubusercontent.com/49544376/92985992-2bbb3580-f47d-11ea-9220-435bb5171681.png)

so he runs the route from the GY but when he gets to the xp path he tries to cut across to where he died. Is there a way to make him follow the path until he gets near his body or something? Its like he hits the route and then jumps to nearest point where he died instead of following the waypoints until he gets close.

Or am i doing my GY path wrong and need to go all the way to the top of the mountain side essentially?

**Comment by julianperrott** [comment]
I am guessing this is Duskwood ? which has two graveyards are the graveyard path only runs from one of them and if you appear at the other one, the path is wrong ?

**Comment by teehehe** [comment]
this is actually the barrens and i always spawn at the same one its near that middle town

**Comment by julianperrott** [comment]
I think that this is a bug.

**Comment by teehehe** [comment]
ya ive seen it other places but since this issue ive tried to make smaller routes that are near the GY's with no obstacles anywhere in path but ive seen it happen randomly

**Comment by julianperrott** [comment]
Adding pathing into the bot so it can find its own way from the graveyard to the corpse.
