### ISSUE TITLE
[Request] Dark Mode/Night Mode on webpage

### ISSUE THREAD

**Issue by teehehe** [julianperrott/WowClassicGrindBot#21]
basically fill the webpage background with a grey color or something so its not super bright(white) at night or in the dark

**Comment by julianperrott** [comment]
Hi, I have added some css to do a gray mode. You will need to uncomment the code below (remove the /* and */) in [site.css](https://github.com/julianperrott/WowClassicGrindBot/blob/master/BlazorServer/wwwroot/css/site.css)

/*
body, table, .card-body {
    background-color: grey !important
}

.card-header, .card-header table {
    background-color: darkgray !important
}
*/
