### ISSUE TITLE
resolution throws off the blackbar over character name

### ISSUE THREAD

**Issue by teehehe** [julianperrott/WowClassicGrindBot#22]
not a big deal but in the web interface depending on your resolution the bar can be off

this was 800x600

![nametag](https://user-images.githubusercontent.com/49544376/93009689-9639a780-f549-11ea-93e4-75c95ad7e636.png)

**Comment by julianperrott** [comment]
800x600 !

Edit the code in DoScreenshot in [WowScreen.cs](https://github.com/julianperrott/WowClassicGrindBot/blob/master/Libs/Screen/WowScreen.cs) to change the rectangle location and size:

` 
    using (var blackPen = new SolidBrush(Color.Black))
     {
    gr.FillRectangle(blackPen, new Rectangle(new Point(bitmap.Width / 15, bitmap.Height / 40), new Size(bitmap.Width / 15, bitmap.Height / 40)));
    }
`

https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics.fillrectangle?view=dotnet-plat-ext-3.1

**Comment by teehehe** [comment]
i am running it on a vmware machine so that i can actually do other things while grinding lol

**Comment by julianperrott** [comment]
Just be careful if you share any screen shots / video ;)
