### ISSUE TITLE
Blacklisted: Target is not a normal mob

### ISSUE THREAD

**Issue by bepehr** [julianperrott/WowClassicGrindBot#23]
Hi , Thank you for your works
I just installed the bot  , and i this error

11:31:30 | Blacklisted: Target is not a normal mob

in addon config page it says i cant find class 

ty

**Comment by julianperrott** [comment]
HI, Target is not a normal mob means you are probably targetting a friendly NPC.

Did you follow these steps on the config page:

https://raw.githubusercontent.com/julianperrott/WowClassicGrindBot/master/images/AddonConfig.png

**Comment by bepehr** [comment]
issue is solved , maybe i did something wrong in config but its fine now , thank you
