### ISSUE TITLE
questing

### ISSUE THREAD

**Issue by viktorblack** [julianperrott/WowClassicGrindBot#28]
is there a way for the bot to do simple kill/items quest? 
i know the bot is made for grinding but with the recent updates and stuff i figured i can just ask

p.s love the work you been doing

**Comment by julianperrott** [comment]
Hi, In theory it shouldn't be too hard to add a single quest.  i.e. do some grinding, then once you have a certain number of items in your bag to go to a npc and hand them in. I have only just added vendoring so there are still bugs with it and it only works with NPCs out in the open e.g. Arathi Highlands, it is not working very well with NPCs in Tanaris as it gets stuck on the door.

What quests were you thinking of ?

**Comment by viktorblack** [comment]
hey thanks for the response well in all honestly i just started doing reputation farm for Wintersaber Trainers (it sucks the life out of me) and was thinking if the bot could do the easy quest that it would be nice :) [https://classic.wowhead.com/quest=4970/frostsaber-provisions](url) but yeah there are a shit ton of simple quest in the game that is just like kill x amount

**Comment by julianperrott** [comment]
I have updated the npc code (vendor / repair) to be more generic see the readme section "NPC Goals". See Paladin.json for an example of the NPC section in the config.

I haven't tried it but I think something like this might work:

       {
          "Name": "Handin",
          "Key": "K",
	  "Requirements": ["BagItem:12622:5","BagItem:12623:5"]
          "PathFilename": "ShortPathToNPC.json",
          "Cost": 6
        }

I'm not sure it is needed though, can't you let the bot grind for a while, then do a mass handing using an addon ?

**Comment by viktorblack** [comment]
i keep getting this error when i start up 👍 

C:\WowClassicGrindBot\BlazorServer>start "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "http://localhost:5000"

C:\WowClassicGrindBot\BlazorServer>c:

C:\WowClassicGrindBot\BlazorServer>cd C:\WowClassicGrindBot\BlazorServer

C:\WowClassicGrindBot\BlazorServer>dotnet run
Goals\VendorGoal.cs(79,37): error CS0115: 'VendorGoal.GetTargetLocation()': no suitable method found to override [C:\WowClassicGrindBot\Libs\Libs.csproj]
Goals\RepairGoal.cs(63,37): error CS0115: 'RepairGoal.GetTargetLocation()': no suitable method found to override [C:\WowClassicGrindBot\Libs\Libs.csproj]

The build failed. Fix the build errors and run again.

C:\WowClassicGrindBot\BlazorServer>pause
Press any key to continue . . .

**Comment by viktorblack** [comment]
so i fixed it to run the bot but now if i put in the code :
		{
          "Name": "Handin",
          "Key": "K",
          "Requirements": ["BagItem:12622:5","BagItem:12623:5"],
          "PathFilename": "Tanaris_GadgetzanKrinkleGoodsteel.json",
          "Cost": 6
        }

i get :
[23:12:41 INF] Program.Main(): After parsing a value an unexpected character was encountered: ". Path 'NPC.Sequence[2].Requirements', line 107, position 63.

**Comment by viktorblack** [comment]
okay found out wat it was "Requirements": ["BagItem:12622:5", "BagItem:12623:5"], there was a space needed
