### ISSUE TITLE
Configuration does not find 100 data frames.

### ISSUE THREAD

**Issue by KasperBaun** [julianperrott/WowClassicGrindBot#3]
Is it a possibility that the colour configuration of the screen has anything to do with it?
I simply cannot get the bot to find 100 data frames when i try to configure it.
![image](https://user-images.githubusercontent.com/43874899/86117382-3184ba00-bacf-11ea-81b0-99632f45be88.png)

**Comment by KasperBaun** [comment]
Fixed by changing settings in the wow game client.
System>Advanced>Constrast from 57 to 50
System>Advanced>Brightness from 48 to 50
System>Advanced>Gamma from 1.2 to 1.0

**Comment by julianperrott** [comment]
hi, that screen shot looks like you are not in the config mode did you type /dc in the wow chat window ?

**Comment by KasperBaun** [comment]
Thanks for replying! I might have made the mistake to not have /dc on when taking the picture because i switched it on and off so many times :-)
The problem was solved by changing the Contrast, brightness and gamma settings though!
