### ISSUE TITLE
Goals\RepairGoal.cs(63,37): error CS0115: 'RepairGoal.GetTargetLocation()': no suitable method found 

### ISSUE THREAD

**Issue by viktorblack** [julianperrott/WowClassicGrindBot#32]
i keep getting this error when i start up 👍

C:\WowClassicGrindBot\BlazorServer>start "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "http://localhost:5000"

C:\WowClassicGrindBot\BlazorServer>c:

C:\WowClassicGrindBot\BlazorServer>cd C:\WowClassicGrindBot\BlazorServer

C:\WowClassicGrindBot\BlazorServer>dotnet run
Goals\VendorGoal.cs(79,37): error CS0115: 'VendorGoal.GetTargetLocation()': no suitable method found to override [C:\WowClassicGrindBot\Libs\Libs.csproj]
Goals\RepairGoal.cs(63,37): error CS0115: 'RepairGoal.GetTargetLocation()': no suitable method found to override [C:\WowClassicGrindBot\Libs\Libs.csproj]

The build failed. Fix the build errors and run again.

C:\WowClassicGrindBot\BlazorServer>pause
Press any key to continue . .

**Comment by julianperrott** [comment]
Please get the latest code as I have rewritten the NPC goals, please see the readme section 'NPC Goals'. I have removed VendorGoal.cs and RepairGoal.cs so perhaps you need to delete these files manually if you are just overwriting from a zip file.. Backup your class json and config.json so they don't get lost.
