### ISSUE TITLE
Doesn't go into "unstick" properly in ghost path

### ISSUE THREAD

**Issue by LeonardWarrior** [julianperrott/WowClassicGrindBot#36]
After dying and the bot calculating a path back to the corpse from the graveyard, it can still get semi-stuck on trees and smaller obstacles etc. This should easily be fixed using the StuckDetector-logic. 

But it seems it only went into the "first" part of the StuckDetection-logic and only being stuck for 3-4s and performing a jump then going back to the path....not getting out and then again going to "stuck" and only jumping. This made it so being stucks was never incremented more than 4 seconds so it never went to the next level of stuck detection.

**Comment by julianperrott** [comment]
Should be fixed now.
