### ISSUE TITLE
WPL don't work for horde

### ISSUE THREAD

**Issue by LeonardWarrior** [julianperrott/WowClassicGrindBot#38]
The graveyard in WPL is in Tirisfal Glades (for horde) so the spiritpath can't be calculated. This might be to much to fix...maybe add an exception in readme

**Comment by julianperrott** [comment]
Pathing will now remember the zone you started in and all paths will end in that zone. So as long as the bot has made at least one path while alive, it should be able to find its way back to the corpse. Of course this will only work if pathing is working (you have the MPQ file), it won't work with the fallback defined spirit path.
