### ISSUE TITLE
unable to find Auc-Stat-Simple.lua.location

### ISSUE THREAD

**Issue by redxking** [julianperrott/WowClassicGrindBot#4]
Following the instructions i get an error pointing to "Auc-Stat-Simple.lua.location" you have it saved to your D:\github\ however that file isnt in any path on my system. I have tried both classic and retail. can you send me a copy of that file? nick.pseftis@gmail.com

**Comment by julianperrott** [comment]
The contents of this file should be the path to your auctioneer file, it is not essential.

`D:\World of Warcraft Classic\World of Warcraft\_classic_\WTF\Account\MYACCOUNTNAME\SavedVariables\Auc-Stat-Simple.lua`

**Comment by julianperrott** [comment]
Added a warning rather than an error in the log for this issue.
