### ISSUE TITLE
Monitor Combat log

### ISSUE THREAD

**Issue by redxking** [julianperrott/WowClassicGrindBot#5]
If combat log to things like Dodge, Block, Parry treat them like a buff so in the rotation you can say requirement has Dodge, Block or Parry execute "Revenge"

**Comment by julianperrott** [comment]
That is an interesting idea. But this is just a simple grind bot and for my purposes it works well enough.

**Comment by julianperrott** [comment]
I have thought about this and I don't think it is going to useful to most classes.
