### ISSUE TITLE
Tightness to Route

### ISSUE THREAD

**Issue by teehehe** [julianperrott/WowClassicGrindBot#9]
is there a way to control how close to the location he walks example walking thru a cave or dungeon requires almost exact coordinates. Also is there a way to manually add coordinates sooner than the record does. example walking through a dungeon or navigating thru a cave may require more coordinates sooner than record is recording. This would also improve corpse running back sometimes get stuck on a tree or inside the graveyard itself or a mountain range because hes to far over from the point.

do you have discord?

**Comment by julianperrott** [comment]
When the bot moves towards a point it sets its heading, it only adjusts this heading if it is not getting closer to the point.

See in [FollowRouteGoal.cs](https://github.com/julianperrott/WowClassicGrindBot/blob/master/Libs/Goals/FollowRouteGoal.cs])
```
   private async Task AdjustHeading(double heading)
        {
            var diff1 = Math.Abs(RADIAN + heading - playerReader.Direction) % RADIAN;
            var diff2 = Math.Abs(heading - playerReader.Direction - RADIAN) % RADIAN;

            var wanderAngle = 0.3;

            if (this.classConfiguration.Mode != Mode.AttendedGather)
            {
                wanderAngle = 0.05;
            }

            if (Math.Min(diff1, diff2) > wanderAngle)
            {
                logger.LogInformation("Correct direction");
                await playerDirection.SetDirection(heading, points.Peek(), "Correcting direction");
            }
            else
            {
                logger.LogInformation($"Direction ok heading: {heading}, player direction {playerReader.Direction}");
            }
        }
```
so you could call this more often in the PerformAction method. Currenly Mode.AttendedGather does this, line 157, remove the If and just always do it ! Also play with the wanderAngle value.
```
 if (this.classConfiguration.Mode == Mode.AttendedGather)
            {
                await AdjustHeading(heading);
            }
```
to
```
                await AdjustHeading(heading);
```

Also perhaps change how close the bot needs to be to a point to determine that it has reached it and starts moving to the next one. See line 269

```
        private int PointReachedDistance()
        {
            if (this.playerReader.PlayerClass == PlayerClassEnum.Druid && this.playerReader.Druid_ShapeshiftForm == ShapeshiftForm.Druid_Travel)
            {
                return 50;
            }

            return (this.playerReader.PlayerBitValues.IsMounted ? 50 : 40);
        }
```

It would take some tweaking of PointReachedDistance() and  wanderAngle.
